# Generated by Django 2.2 on 2020-02-08 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_creator_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='category',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='full_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='topic',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
