# Generated by Django 2.2 on 2020-02-08 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200208_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='creators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, null=True)),
                ('image', models.CharField(max_length=500, null=True)),
                ('topic', models.CharField(max_length=500, null=True)),
                ('category', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='creator',
        ),
    ]
