# Generated by Django 2.2 on 2020-02-08 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200208_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='creators',
            name='discription',
            field=models.CharField(default=django.utils.timezone.now, max_length=3500),
            preserve_default=False,
        ),
    ]
